//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// RVision.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RVISION_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_RVISION_ALIGN               133
#define IDD_DRAW_ALIGN                  135
#define IDD_RVISION_REVIEW              137
#define IDD_DRAW_REVIEW                 139
#define IDD_RVISION_FC                  142
#define IDD_DRAW_FC                     144
#define IDB_BITMAP_ANGLE_OFF            147
#define IDB_BITMAP_ANGLE_ON             148
#define IDB_BITMAP_DISTANCE_OFF         149
#define IDB_BITMAP_DISTANCE_ON          150
#define IDB_BITMAP_GRAPHIC_OFF          151
#define IDB_BITMAP_GRAPHIC_ON           152
#define IDB_BITMAP_LINE_OFF             153
#define IDB_BITMAP_LINE_ON              154
#define IDB_BITMAP_RECTANGLE_OFF        155
#define IDB_BITMAP_RECTANGLE_ON         156
#define IDB_BITMAP_CLEAR                157
#define IDB_BITMAP_LOGIN                158
#define IDB_BITMAP_LOGOUT               159
#define IDB_BITMAP_ZOOMIN               160
#define IDB_BITMAP_ZOOMOUT              161
#define IDB_BITMAP_REG_EDGE             162
#define IDB_BITMAP_REG_MARK             163
#define IDD_RVISION_SETTING             164
#define IDD_SETTING_CAMERA              169
#define IDD_SETTING_ALIGN               173
#define IDD_SETTING_NUMPAD              176
#define IDD_SETTING_FC                  179
#define IDD_POPUP_MANUALALIGN           182
#define IDD_DRAW_MANUALALIGN            184
#define IDB_BITMAP_LED_OFF              188
#define IDB_BITMAP_LED_ON               189
#define IDB_BITMAP_CIRCLE_OFF           191
#define IDB_BITMAP_CIRCLE_ON            192
#define IDD_POPUP_RECIPE_SELECT         193
#define IDD_POPUP_RECIPE_ADD            195
#define IDB_BITMAP_LED_OFF2             198
#define IDB_BITMAP_LED_ON2              199
#define IDB_BITMAP_RECONNECT            201
#define IDD_POPUP_ALARM                 202
#define IDD_DRAW_SCALE_H                204
#define IDB_BITMAP_CENTERDIST_OFF       206
#define IDB_BITMAP2                     207
#define IDB_BITMAP_CENTERDIST_ON        207
#define IDD_SETTING_ALIGNMARK           208
#define IDD_SETTING_LASER               213
#define IDD_POPUP_PREPROCESS_IMG        216
#define IDB_BITMAP_EDGEPOS              220
#define IDB_BITMAP_MARKPOS              221
#define IDD_SETTING_HIDE                222
#define IDD_SETTING_ALIGN_METHOD        224
#define IDB_BITMAP_12                   242
#define IDB_BITMAP_13                   243
#define IDB_BITMAP_24                   244
#define IDB_BITMAP_34                   245
#define IDB_BITMAP_ALL                  246
#define IDB_BITMAP_123                  247
#define IDB_BITMAP_124                  248
#define IDB_BITMAP_134                  249
#define IDB_BITMAP_234                  250
#define IDC_BTN_MODE_ALIGN              1000
#define IDC_BTN_MODE_REVIEW             1001
#define IDC_BTN_MODE_FC                 1002
#define IDC_BTN_MODE_SETTING            1003
#define IDC_ICON_LOGIN                  1004
#define IDC_GRP_DETECTION               1005
#define IDC_GRP_MODIFY                  1006
#define IDC_STATIC_ALIGN1               1007
#define IDC_GRP_POINT                   1007
#define IDC_GRP_DETECT                  1007
#define IDC_STATIC_ALIGN2               1008
#define IDC_ICON_ALIGN1                 1008
#define IDC_GRP_JUDGE                   1008
#define IDC_STATIC_ALIGN3               1009
#define IDC_ICON_ALIGN2                 1009
#define IDC_GRP_MATCHRATE               1009
#define IDC_STATIC_ALIGN4               1010
#define IDC_ICON_ALIGN3                 1010
#define IDC_STATIC_ALIGN1_MATCHRATE     1011
#define IDC_ICON_ALIGN4                 1011
#define IDC_STATIC_ALIGN1_X             1011
#define IDC_STATIC_ALIGN2_MATCHRATE     1012
#define IDC_ICON_REVIEW                 1012
#define IDC_STATIC_ALIGN1_Y             1012
#define IDC_STATIC_ALIGN3_MATCHRATE     1013
#define IDC_ICON_LIGHT                  1013
#define IDC_STATIC_ALIGN2_X             1013
#define IDC_STATIC_ALIGN4_MATCHRATE     1014
#define IDC_STATIC_ALIGN2_Y             1014
#define IDC_STATIC_ALIGN1_JUDGE         1015
#define IDC_STATIC_ALIGN3_X             1015
#define IDC_STATIC_ALIGN2_JUDGE         1016
#define IDC_STATIC_ALIGN3_Y             1016
#define IDC_STATIC_ALIGN3_JUDGE         1017
#define IDC_STATIC_ALIGN4_X             1017
#define IDC_STATIC_ALIGN4_JUDGE         1018
#define IDC_STATIC_ALIGN4_Y             1018
#define IDC_STATIC_MATCHRATE            1019
#define IDC_STATIC_JUDGE                1020
#define IDC_STATIC_ERROR_X              1020
#define IDC_STATIC_TITLE                1021
#define IDC_STATIC_REPEAT               1021
#define IDC_STATIC_MODIFY_X             1021
#define IDC_STATIC_ERROR_Y              1021
#define IDC_STATIC_SUBTITLE             1022
#define IDC_STATIC_MODIFY_Y             1022
#define IDC_STATIC_MATCHRATE_VALUE      1022
#define IDC_STATIC_TOTALJUDGE           1023
#define IDC_STATIC_MODIFY_T             1023
#define IDC_STATIC_ERROR_X_VALUE        1023
#define IDC_STATIC_XMODIFY              1024
#define IDC_STATIC_ERROR_Y_VALUE        1024
#define IDC_STATIC_YMODIFY              1025
#define IDC_STATIC_TMODIFY              1026
#define IDC_STATIC_MODIFY_VALUE         1027
#define IDC_STATIC_MODIFY_JUDGE         1028
#define IDC_STATIC_XMODIFY_VALUE        1029
#define IDC_STATIC_YMODIFY_VALUE        1030
#define IDC_STATIC_TMODIFY_VALUE        1031
#define IDC_STATIC_XMODIFY_JUDGE        1032
#define IDC_STATIC_YMODIFY_JUDGE        1033
#define IDC_STATIC_TMODIFY_JUDGE        1034
#define IDC_LIST_ALIGNLOG               1035
#define IDC_PIC_NAVIGATOR               1036
#define IDC_STATIC_PROCTIME             1036
#define IDC_LIST_MEASUREMENT            1037
#define IDC_STATIC_LEVEL_JUDGE          1037
#define IDC_STATIC_LEVEL_H_JUDGE        1038
#define IDC_STATIC_LEVEL_V_JUDGE        1039
#define IDC_STATIC_LEVEL_H_VALUE        1039
#define IDC_STATIC_MISTAKE_JUDGE        1040
#define IDC_STATIC_MISTAKE_VALUE        1041
#define IDC_BTN_SAVE                    1045
#define IDC_BTN_CAPTURE                 1046
#define IDC_STATIC_MAGNI                1049
#define IDC_BTN_REG_MARK                1050
#define IDC_BTN_REG_EDGE                1051
#define IDC_PIC_REG_MARK                1052
#define IDC_PIC_FIND_MARK               1053
#define IDC_STATIC_GAIN                 1054
#define IDC_STATIC_NEWCAL               1055
#define IDC_STATIC_POINT                1056
#define IDC_STATIC_LENGTH               1057
#define IDC_STATIC_OLDCTFILE            1058
#define IDC_STATIC_NEWCTFILE            1059
#define IDC_EDIT_GAIN                   1060
#define IDC_EDIT_NEWCAL                 1061
#define IDC_EDIT_POINT_X                1062
#define IDC_EDIT_POINT_Y                1063
#define IDC_EDIT_LENGTH_X               1064
#define IDC_EDIT_LENGTH_Y               1065
#define IDC_EDIT_OLDCTFILE              1066
#define IDC_EDIT_NEWCTFILE              1067
#define IDC_LIST_FC                     1068
#define IDC_BTN_MODE                    1078
#define IDC_PIC_ALIGN1                  1080
#define IDC_BTN_LINE                    1081
#define IDC_PIC_ALIGN2                  1081
#define IDC_PIC_REVIEW                  1081
#define IDC_BTN_RECTANGLE               1082
#define IDC_PIC_ALIGN3                  1082
#define IDC_PIC_FC                      1082
#define IDC_PIC_ALIGN4                  1083
#define IDC_PIC_SETTING                 1083
#define IDC_BTN_ANGLE                   1084
#define IDC_BTN_CLEAR                   1085
#define IDC_BTN_ALIGN1                  1085
#define IDC_BTN_ZOOMIN                  1086
#define IDC_BTN_ALIGN2                  1086
#define IDC_BTN_ZOOMOUT                 1087
#define IDC_BTN_ALIGN3                  1087
#define IDC_BTN_ALIGN4                  1088
#define IDC_BTN_CLEARALL                1088
#define IDC_BTN_REVIEW                  1089
#define IDC_BTN_SETTING                 1089
#define IDC_BTN_CIRCLE                  1089
#define IDC_SLIDER_EXPOSURETIME         1090
#define IDC_BTN_MARK                    1090
#define IDC_BTN_CENTER_DIST             1090
#define IDC_SLIDER_LIGHT                1091
#define IDC_BTN_EDGE                    1091
#define IDC_SLIDER_LIGHT_ALIGN1         1091
#define IDC_EDIT_EXPOSURETIME           1092
#define IDC_SLIDER_LIGHT_ALIGN2         1092
#define IDC_BTN_ALIGN_METHOD            1092
#define IDC_EDIT_LIGHT                  1093
#define IDC_EDIT_LIGHT_ALIGN1           1093
#define IDC_BTN_OFFSET                  1093
#define IDC_STATIC_EXPOSURETIME         1094
#define IDC_SLIDER_LIGHT_ALIGN3         1094
#define IDC_STATIC_LIGHT                1095
#define IDC_STATIC_LIGHT_ALIGN1         1095
#define IDC_STATIC_LIGHT_ALL            1096
#define IDC_EDIT_NAME                   1096
#define IDC_SLIDER_LIGHT_ALIGN4         1096
#define IDC_STATIC_EXPOSURETIME_ALL     1097
#define IDC_SLIDER_LIGHT_REVIEW         1097
#define IDC_STATIC_NAME                 1098
#define IDC_EDIT_LIGHT_ALIGN2           1098
#define IDC_STATIC_CROSSLINE            1099
#define IDC_EDIT_LIGHT_ALIGN3           1099
#define IDC_STATIC_ALIGNJUDGE           1100
#define IDC_EDIT_LIGHT_ALIGN4           1100
#define IDC_GRP_DISPLAY                 1101
#define IDC_CHK_NAME                    1102
#define IDC_CHK_CROSSLINE               1103
#define IDC_CHK_ALIGNJUDGE              1104
#define IDC_CHK_DETECTRANGE             1104
#define IDC_CHK_ROI                     1104
#define IDC_GRP_LIGHT                   1105
#define IDC_COLOR_NAME                  1106
#define IDC_COLOR_CROSSLINE             1107
#define IDC_CHK_EXPOSURETIME            1108
#define IDC_COLOR_ALIGNRANGE            1108
#define IDC_CHK_DETECTEDGE              1108
#define IDC_COLOR_ROI                   1108
#define IDC_CHK_LIGHT                   1109
#define IDC_COLOR_DETECTRANGE           1109
#define IDC_EDIT_LIGHT_REVIEW           1109
#define IDC_BTN_APPLY                   1110
#define IDC_BTN_CANCEL                  1111
#define IDC_BTN_MODIFY                  1112
#define IDC_BTN_CAMERA                  1113
#define IDC_CHK_ALIGNRANGE              1113
#define IDC_COLOR_DETECTEDGE            1113
#define IDC_STATIC_LIGHT_ALIGN2         1113
#define IDC_STATIC_LIGHT_ALIGN3         1114
#define IDC_BTN_ALIGN                   1115
#define IDC_GRP_EDGE                    1115
#define IDC_STATIC_LIGHT_ALIGN4         1115
#define IDC_BTN_FC                      1116
#define IDC_STATIC_LIGHT_REVIEW         1116
#define IDC_BTN_ADD                     1117
#define IDC_BTN_LASER                   1117
#define IDC_BTN_RECIPE_LOAD             1118
#define IDC_BTN_ALIGNMARK               1118
#define IDC_BTN_EDGE_ROI_START_X        1129
#define IDC_STATIC_START                1130
#define IDC_EDIT_EDGE_ROI_START_X       1131
#define IDC_EDIT_EDGE_ROI_START_Y       1132
#define IDC_EDIT_EDGE_ROI_END_X         1133
#define IDC_EDIT_EDGE_ROI_END_Y         1134
#define IDC_BTN_EDGE_FIND               1139
#define IDC_BTN_LTOR                    1142
#define IDC_BTN_RTOL                    1143
#define IDC_BTN_EDGE_ROI_START_Y        1144
#define IDC_BTN_EDGE_ROI_END_X          1145
#define IDC_BTN_EDGE_ROI_END_Y          1146
#define IDC_STATIC_END                  1147
#define IDC_STATIC_METHOD               1148
#define IDC_STATIC_JUDGE_RANGE_X        1149
#define IDC_EDIT_BINARY_LOW             1150
#define IDC_EDIT_BINARY_HIGH            1151
#define IDC_EDIT_NUMBER_BEFORE          1151
#define IDC_BTN_BINARY_LOW              1152
#define IDC_BTN_BACKSPACE               1152
#define IDC_EDIT_LEVEL_H_RANGE          1152
#define IDC_EDIT_FC_OPEN                1152
#define IDC_BTN_BINARY_HIGH             1153
#define IDC_BTN_NUM0                    1153
#define IDC_EDIT_LEVEL_V_RANGE          1153
#define IDC_EDIT_X_RANGE                1153
#define IDC_EDIT_FC_CLOSE               1153
#define IDC_STATIC_BINARY               1154
#define IDC_BTN_NUM1                    1154
#define IDC_BTN_NUM2                    1155
#define IDC_STATIC_JUDGE_RANGE_Y        1155
#define IDC_EDIT_ALIGN_MATCHRATE        1155
#define IDC_EDIT_FCMARK_BINARY_LOW      1155
#define IDC_BTN_NUM3                    1156
#define IDC_STATIC_JUDGE_RANGE_T        1156
#define IDC_EDIT_Y_RANGE                1156
#define IDC_STATIC_FCMARK_BINARY        1156
#define IDC_BTN_NUM4                    1157
#define IDC_BTN_UTOD                    1157
#define IDC_EDIT_T_RANGE                1157
#define IDC_BTN_NUM5                    1158
#define IDC_BTN_DTOU                    1158
#define IDC_EDIT_LEVEL_RANGE            1158
#define IDC_BTN_NUM6                    1159
#define IDC_EDIT_MISTAKE_RANGE          1159
#define IDC_BTN_NUM7                    1160
#define IDC_EDIT_JUDGE_RANGE_X          1160
#define IDC_BTN_NUM8                    1161
#define IDC_EDIT_JUDGE_RANGE_Y          1161
#define IDC_BTN_NUM9                    1162
#define IDC_EDIT_JUDGE_RANGE_T          1162
#define IDC_BTN_DOT                     1163
#define IDC_BTN_DELETE                  1164
#define IDC_EDIT_NUMBER_AFTER           1165
#define IDC_STATIC_BEFORE               1166
#define IDC_STATIC_AFTER                1167
#define IDC_GRP_JUDGE_RANGE             1167
#define IDC_STATIC_MARK                 1168
#define IDC_GRP_ALIGNCAM_POS            1168
#define IDC_STATIC_DETECT               1169
#define IDC_GRP_ENROLL                  1169
#define IDC_GRP_RANGE                   1169
#define IDC_BTN_MARK_ENROLL             1170
#define IDC_BTN_EDGE_ENROLL             1171
#define IDC_BTN_MARK_APPLY              1171
#define IDC_EDIT_MATCHRATE              1172
#define IDC_BTN_MARK_CANCEL             1172
#define IDC_BTN_FCMARK_CANCEL           1173
#define IDC_EDIT_REPEAT                 1174
#define IDC_BTN_PREPROCESS_APPLY        1174
#define IDC_EDIT_FC_ROI_START_X         1175
#define IDC_BTN_PREPROCESS_CANCEL       1175
#define IDC_BTN_PREPROCESS_SHOW         1175
#define IDC_BTN_FC_ROI_START_X          1176
#define IDC_BTN_FCMARK_PREPROCESS_CANCEL 1176
#define IDC_EDIT_FC_ROI_START_Y         1177
#define IDC_BTN_FC_ROI_START_Y          1178
#define IDC_BTN_PREPROCESS_SHOW2        1178
#define IDC_EDIT_FC_ROI_END_X           1179
#define IDC_BTN_FC_ROI_END_X            1180
#define IDC_EDIT_FC_ROI_END_Y           1181
#define IDC_BTN_FC_ROI_END_Y            1182
#define IDC_STATIC_SELECTCAM            1197
#define IDC_CMB_SELECTCAM               1198
#define IDC_STATIC_MODIFY_X_VALUE       1199
#define IDC_STATIC_MODIFY_Y_VALUE       1200
#define IDC_STATIC_MODIFY_T_VALUE       1201
#define IDC_STATIC_ALIGN_1              1202
#define IDC_STATIC_ALIGN_2              1203
#define IDC_STATIC_ALIGN_3              1204
#define IDC_STATIC_ALIGN_4              1205
#define IDC_BTN_MANUALALIGN             1206
#define IDC_STATIC_ALIGN_1_DETECT       1206
#define IDC_STATIC_ALIGN_1_X            1207
#define IDC_CHK_MARK                    1207
#define IDC_STATIC_ALIGN_2_DETECT       1207
#define IDC_STATIC_ALIGN_2_X            1208
#define IDC_CHK_EDGE                    1208
#define IDC_STATIC_ALIGN_3_DETECT       1208
#define IDC_STATIC_ALIGN_3_X            1209
#define IDC_PIC_MARK_DETECT             1209
#define IDC_STATIC_ALIGN_4_DETECT       1209
#define IDC_STATIC_ALIGN_4_X            1210
#define IDC_PIC_MARK_ENROLL             1210
#define IDC_EDIT_ALIGN1_X               1210
#define IDC_STATIC_MATCHRATE_1          1210
#define IDC_STATIC_ALIGN_1_Y            1211
#define IDC_EDIT_ALIGN1_Y               1211
#define IDC_STATIC_MATCHRATE_2          1211
#define IDC_STATIC_ALIGN_2_Y            1212
#define IDC_EDIT_ALIGN2_X               1212
#define IDC_STATIC_MATCHRATE_3          1212
#define IDC_STATIC_ALIGN_3_Y            1213
#define IDC_EDIT_ALIGN2_Y               1213
#define IDC_STATIC_MATCHRATE_4          1213
#define IDC_STATIC_ALIGN_4_Y            1214
#define IDC_EDIT_ALIGN3_X               1214
#define IDC_STATIC_MATCHRATE_VALUE_1    1214
#define IDC_STATIC_POINT_X              1215
#define IDC_EDIT_ALIGN3_Y               1215
#define IDC_STATIC_MATCHRATE_VALUE_2    1215
#define IDC_STATIC_POINT_Y              1216
#define IDC_EDIT_ALIGN4_X               1216
#define IDC_STATIC_LENGTH_X             1216
#define IDC_STATIC_MATCHRATE_VALUE_3    1216
#define IDC_EDIT_ALIGN4_Y               1217
#define IDC_STATIC_MANUALALIGN          1217
#define IDC_STATIC_MATCHRATE_VALUE_4    1217
#define IDC_STATIC_MODIFY_X_JUDGE       1217
#define IDC_PIC_ALIGNMARK_ENROLL        1218
#define IDC_STATIC_MATCHRATE_JUDGE_1    1218
#define IDC_STATIC_MODIFY_Y_JUDGE       1218
#define IDC_STATIC_MATCHRATE_JUDGE_2    1219
#define IDC_STATIC_MODIFY_T_JUDGE       1219
#define IDC_PIC_ALIGNMARK_DETECT        1220
#define IDC_STATIC_MATCHRATE_JUDGE_3    1220
#define IDC_BTN_FCMARK_ENROLL           1221
#define IDC_STATIC_MATCHRATE_JUDGE_4    1221
#define IDC_BTN_FCMARK_APPLY            1222
#define IDC_PIC_MANUALALIGN             1223
#define IDC_BTN_POINT                   1224
#define IDC_ICON_ALIGN                  1226
#define IDC_ICON_HANDLE                 1227
#define IDC_ICON_HEARTBEAT              1228
#define IDC_BTN_OLDCTFILE               1229
#define IDC_ICON_CAMERA_1               1229
#define IDC_ICON_CAM1                   1229
#define IDC_BTN_NEWCTFILE               1230
#define IDC_STATIC_LEVEL                1230
#define IDC_ICON_CAMERA_2               1230
#define IDC_ICON_CAM2                   1230
#define IDC_STATIC_LEVEL_VALUE          1231
#define IDC_STATIC_LEVEL_H              1231
#define IDC_ICON_CAMERA_3               1231
#define IDC_GRP_ROI                     1232
#define IDC_STATIC_LEVEL_V              1232
#define IDC_ICON_CAMERA_4               1232
#define IDC_ICON_CAM3                   1232
#define IDC_GRP_FC_PARAM                1233
#define IDC_BTN_MEASUREMENT             1233
#define IDC_STATIC_MISTAKE              1233
#define IDC_GRP_MARK                    1233
#define IDC_ICON_CAMERA_5               1233
#define IDC_PROGRESS_LIGHT1             1234
#define IDC_STATIC_LEVEL_V_RANGE        1234
#define IDC_ICON_CAM4                   1234
#define IDC_GRP_PREPROCESS              1234
#define IDC_GRP_MEASURE                 1234
#define IDC_PROGRESS_LIGHT2             1235
#define IDC_EDIT_RECIPE_SELECT          1235
#define IDC_ICON_CAM5                   1235
#define IDC_PROGRESS_LIGHT3             1236
#define IDC_EDIT_RECIPE_NAME            1236
#define IDC_PROGRESS_LIGHT4             1237
#define IDC_GRP_PARAM                   1237
#define IDC_GRP_MEASUREMENT             1237
#define IDC_PROGRESS_LIGHT5             1238
#define IDC_GRP_RESULT                  1238
#define IDC_SLIDER_LIGHT_1              1238
#define IDC_GRP_POSTPROCESS             1238
#define IDC_SLIDER_LIGHT_2              1239
#define IDC_PIC_MARK                    1239
#define IDC_SLIDER_LIGHT_3              1240
#define IDC_STATIC_LEVEL_H_RANGE        1240
#define IDC_SLIDER_LIGHT_4              1241
#define IDC_STATIC_X_RANGE              1241
#define IDC_SLIDER_LIGHT_5              1242
#define IDC_STATIC_Y_RANGE              1242
#define IDC_EDIT_RECIPE                 1242
#define IDC_STATIC_T_RANGE              1243
#define IDC_STATIC_RECIPE               1243
#define IDC_CMB_RECIPE_SELECT           1244
#define IDC_STATIC_LEVEL_RANGE          1244
#define IDC_CMB_RECIPE_ADD              1245
#define IDC_STATIC_MISTAKE_RANGE        1245
#define IDC_STATIC_ALIGNRUN             1246
#define IDC_STATIC_ALIGNSTART           1247
#define IDC_STATIC_ALIGNEND             1248
#define IDC_ICON_ALIGNSTART             1249
#define IDC_ICON_ALIGNRUN               1250
#define IDC_ICON_ALIGNEND               1251
#define IDC_STATIC_X_OFFSET             1254
#define IDC_STATIC_Y_OFFSET             1255
#define IDC_EDIT_X_OFFSET               1256
#define IDC_EDIT_Y_OFFSET               1257
#define IDC_STATIC_CHK_HANDLE           1257
#define IDC_STATIC_CHK_HEARTBEAT        1258
#define IDC_STATIC_CHK_CAM1             1259
#define IDC_STATIC_CHK_CAM2             1260
#define IDC_STATIC_CHK_CAM3             1261
#define IDC_STATIC_CHK_CAM4             1262
#define IDC_STATIC_CHK_CAM5             1263
#define IDC_STATIC_RECONNECT            1264
#define IDC_ICON_RECONNECT              1265
#define IDC_STATIC_ALARM                1266
#define IDC_BTN_ALIGNMARK_UP            1267
#define IDC_BTN_ALIGNMARK_DOWN          1268
#define IDC_BTN_ALIGNMARK_LEFT          1269
#define IDC_BTN_ALIGNMARK_RIGHT         1270
#define IDC_BTN_FCMARK_UP               1271
#define IDC_BTN_FCMARK_DOWN             1272
#define IDC_BTN_FCMARK_LEFT             1273
#define IDC_BTN_FCMARK_RIGHT            1274
#define IDC_CHK_SCALE                   1275
#define IDC_EDIT_MARK_THREAD            1276
#define IDC_STATIC_MARK_THREAD          1277
#define IDC_EDIT_MARK_OPEN              1278
#define IDC_BTN_MARK_DETECT             1279
#define IDC_BTN_UP                      1279
#define IDC_STATIC_MARK_MEASURE_X       1279
#define IDC_EDIT_MARK_DETECT_RATE       1280
#define IDC_BTN_DOWN                    1280
#define IDC_STATIC_MARK_MEASURE_X_VALUE 1280
#define IDC_STATIC_MARK_OPEN            1281
#define IDC_BTN_LEFT                    1281
#define IDC_EDIT_MARK_CLOSE             1282
#define IDC_BTN_RIGHT                   1282
#define IDC_STATIC_MARK_CLOSE           1283
#define IDC_BTN_MARK_SET_APPLY          1284
#define IDC_STATIC_MARK_MEASURE_Y       1284
#define IDC_STATIC_DETECT_X             1285
#define IDC_STATIC_MARK_MEASURE_RATE    1285
#define IDC_BTN_MARK_SET_CANCEL         1286
#define IDC_STATIC_MARK_MEASURE_Y_VALUE 1286
#define IDC_BTN_MARK_SET_SAVE           1287
#define IDC_EDIT_XOFFSET                1287
#define IDC_STATIC_MARK_MEASURE_RATE_VALUE 1287
#define IDC_STATIC_DETECT_Y             1288
#define IDC_STATIC_DETECT_RATE          1289
#define IDC_STATIC_DETECT_VALUE_X       1290
#define IDC_STATIC_DETECT_VALUE_Y       1291
#define IDC_STATIC_DETECT_VALUE_RATE    1292
#define IDC_EDIT_YOFFSET                1293
#define IDC_STATIC_XOFFSET              1294
#define IDC_STATIC_YOFFSET              1295
#define IDC_BTN_MARK_REG                1295
#define IDC_BTN_MARK_UP                 1296
#define IDC_STATIC_OPEN                 1296
#define IDC_BTN_MARK_DOWN               1297
#define IDC_STATIC_CLOSE                1297
#define IDC_BTN_MARK_LEFT               1298
#define IDC_STATIC_FCMARK_OPEN          1298
#define IDC_STATIC_TOFFSET              1298
#define IDC_BTN_MARK_RIGHT              1299
#define IDC_EDIT_OPEN                   1299
#define IDC_STATIC_FCMARK_CLOSE         1299
#define IDC_EDIT_CLOSE                  1300
#define IDC_EDIT_FCMARK_OPEN            1300
#define IDC_EDIT_FCMARK_CLOSE           1301
#define IDC_EDIT_TOFFSET                1301
#define IDC_EDIT_MARK_MATCHRATE         1303
#define IDC_STATIC_MARK_MATCHRATE       1304
#define IDC_BTN_MARK_MEASURE            1305
#define IDC_PIC_PREPROCESS              1307
#define IDC_BTN_FCMARK_PREPROCESS_APPLY 1309
#define IDC_PIC_LASER                   1310
#define IDC_STATIC_LASER_SPEED          1311
#define IDC_STATIC_LASER_HZ             1312
#define IDC_STATIC_LASER_SIZE           1313
#define IDC_STATIC_LASER_POWER          1314
#define IDC_BTN_CALCULATION             1315
#define IDC_STATIC_OVERLAP_RATE         1316
#define IDC_EDIT_LASER_SPEED            1317
#define IDC_EDIT_LASER_HZ               1318
#define IDC_EDIT_LASER_SIZE             1319
#define IDC_EDIT_LASER_POWER            1320
#define IDC_STATIC_OVERLAP_RATE_VALUE   1321
#define IDC_STATIC_PTP                  1322
#define IDC_STATIC_PTP_VALUE            1323
#define IDC_PIC_LASERMARK               1324
#define IDC_BTN_LASERMARK_UP            1325
#define IDC_BTN_LASERMARK_LEFT          1326
#define IDC_BTN_LASERMARK_DOWN          1327
#define IDC_BTN_LASERMARK_RIGHT         1328
#define IDC_STATIC_LASERMARK_MATCHRATE  1329
#define IDC_EDIT_LASERMARK_MATCHRATE    1330
#define IDC_BTN_LASERMARK_ENROLL        1331
#define IDC_BTN_LASERMARK_APPLY         1332
#define IDC_BTN_LASERMARK_CANCEL        1333
#define IDC_BTN_LASERMARK_MEASURE       1334
#define IDC_CHK_ALL                     1334
#define IDC_STATIC_LASERMARK_MEASURE_1  1335
#define IDC_PIC_PREPROCESS_IMG          1335
#define IDC_STATIC_LASERMARK_MEASURE_2  1336
#define IDC_BTN_EXIT                    1336
#define IDC_STATIC_LASERMARK_MEASURE_3  1337
#define IDC_STATIC_LASERMARK_MEASURE_VALUE_1 1338
#define IDC_STATIC_LASERMARK_MEASURE_VALUE_2 1339
#define IDC_PIC_MARK_POS                1339
#define IDC_STATIC_LASERMARK_MEASURE_VALUE_3 1340
#define IDC_EDIT_ALIGN_WIDTH            1340
#define IDC_BTN_COLOR                   1340
#define IDC_STATIC_ENERGY               1341
#define IDC_EDIT_ALIGN_HEIGHT           1341
#define IDC_STATIC_ENERGY_VALUE         1342
#define IDC_STATIC_DFOCUS               1343
#define IDC_STATIC_HIDE1                1343
#define IDC_EDIT_DFOCUS                 1344
#define IDC_EDIT_HIDE1                  1344
#define IDC_STATIC_SPOT_ERROR           1345
#define IDC_STATIC_SPOT_ERROR_VALUE     1346
#define IDC_STATIC_HIDE2                1346
#define IDC_BTN_LASERMARK_CLEAR         1347
#define IDC_STATIC_HIDE3                1347
#define IDC_CHK_ALIGN_ALL               1347
#define IDC_STATIC_HIDE4                1348
#define IDC_CHK_ALIGN_12                1348
#define IDC_STATIC_HIDE5                1349
#define IDC_CHK_ALIGN_34                1349
#define IDC_EDIT_HIDE2                  1350
#define IDC_CHK_ALIGN_13                1350
#define IDC_EDIT_HIDE3                  1351
#define IDC_CHK_ALIGN_24                1351
#define IDC_EDIT_HIDE4                  1352
#define IDC_PIC_ALIGN_ALL               1352
#define IDC_EDIT_HIDE5                  1353
#define IDC_PIC_ALIGN_12                1353
#define IDC_PIC_ALIGN_34                1354
#define IDC_PIC_ALIGN_13                1355
#define IDC_PIC_ALIGN_24                1356
#define IDC_PIC_ALIGN_124               1358

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        251
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1353
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
